export const ARCHITECTURE_MD = `
# 🏛️ Enterprise RAG API Assistant Architecture (Comprehensive Guide)

This document provides a highly detailed, end-to-end technical explanation of every component powering the Retrieval-Augmented Generation (RAG) API Assistant. 

## 📋 Table of Contents
1. [High-Level System Overview](#1-high-level-system-overview)
2. [Frontend Architecture (Next.js)](#2-frontend-architecture-nextjs)
3. [Backend Architecture (NestJS)](#3-backend-architecture-nestjs)
4. [Storage & Databases (PostgreSQL & Qdrant)](#4-storage--databases-postgresql--qdrant)
5. [Document Ingestion & Chunking](#5-document-ingestion--chunking)
6. [Embeddings & Vectorization](#6-embeddings--vectorization)
7. [LLM Inference & Streaming](#7-llm-inference--streaming)

---

## 1. High-Level System Overview

The system is designed as a modern, decoupled **Monorepo** consisting of two main services that communicate via RESTful APIs and Server-Sent Events (SSE). 

- **Frontend**: A highly interactive, animated, glassmorphic user interface built with Next.js.
- **Backend**: An orchestration layer built with NestJS that handles file parsing, database management, and LLM communication.
- **Storage**: A dual-database layer using PostgreSQL (for relational data) and Qdrant (for vector embeddings).
- **AI Engine**: A hybrid AI approach using local Ollama instances for embeddings and cloud APIs (Sarvam AI) for generation.

---

## 2. Frontend Architecture (Next.js)

The frontend is a single-page application built using the Next.js App Router (\`apps/frontend\`).

### UI & Styling
- **Tailwind CSS v4**: Used for utility-first styling. The \`globals.css\` file contains a highly customized CSS token system (\`@theme inline\`) that maps colors to a beautiful Dark/Light mode theme using \`oklch\` color spaces.
- **Framer Motion**: Powers all the micro-animations, glassmorphism hover effects, and staggered list entrances.
- **Lucide React**: Provides the clean, modern iconography used throughout the sidebar and dashboards.

### Real-Time Chat & Markdown
- **Server-Sent Events (SSE)**: The chat relies on \`@microsoft/fetch-event-source\` to consume tokens from the backend as they are generated by the LLM. This ensures a zero-latency typing effect.
- **Markdown Parsing**: \`react-markdown\` and \`remark-gfm\` are used to safely render the LLM's text output into HTML. 
- **Reasoning Process Parser**: The UI contains a custom parser that intercepts \`<think>...</think>\` tags generated by reasoning models (like DeepSeek-R1) and neatly folds them into an interactive, collapsible "Reasoning Process" accordion.

---

## 3. Backend Architecture (NestJS)

The backend (\`apps/backend\`) is a heavily modularized API Gateway built with NestJS.

### Core Modules
1. **\`DocumentsModule\`**: Handles file uploads via \`multer\`. It creates temporary files, parses them, and delegates to the vectorization service.
2. **\`VectorizationService\`**: The bridge between raw text and mathematical vectors. It utilizes \`LangChain.js\` to manage the chunking and embedding processes.
3. **\`ConversationsModule\`**: Provides standard REST CRUD endpoints to manage chat history using Prisma.
4. **\`ChatModule\`**: Orchestrates the RAG prompt execution by combining user queries, past chat history, and retrieved Qdrant chunks, then piping the LLM response back as an SSE stream.

### Architecture Patterns
- **Dependency Injection**: Services are injected into Controllers, ensuring business logic is isolated and testable.
- **Prisma ORM**: Provides a strict, type-safe schema linking the TypeScript backend directly to the PostgreSQL tables.

---

## 4. Storage & Databases (PostgreSQL & Qdrant)

The system isolates structured relational data from unstructured mathematical data.

### PostgreSQL (Relational Data)
Powered by Prisma, PostgreSQL stores three primary models:
1. \`Document\`: Tracks uploaded files (\`id\`, \`title\`, \`isIndexed\`).
2. \`Conversation\`: Groups chat sessions (\`id\`, \`title\`).
3. \`Message\`: Stores individual chat bubbles (\`role\`, \`content\`, \`conversationId\`).

### Qdrant (Vector Data)
[Qdrant](https://qdrant.tech/) is a high-performance, open-source vector similarity search engine running in a Docker container.
- **Purpose**: It stores the mathematical representations of text chunks alongside metadata (like the original \`documentId\`).
- **Filtering**: When a user selects a specific document in the UI, the backend sends a strict \`must\` filter to Qdrant. This guarantees the vector search *only* looks at chunks belonging to the selected file.

---

## 5. Document Ingestion & Chunking

Chunking is a critical step in the RAG pipeline. LLMs have limited context windows, so we cannot feed entire PDF books into the prompt. We must break the documents into smaller, searchable pieces.

### How Chunking Works
1. **Parsing**: When a \`.md\`, \`.json\`, \`.yaml\`, or \`.txt\` file is uploaded, the backend reads it into a single raw text string.
2. **RecursiveCharacterTextSplitter**: The backend uses LangChain's chunking algorithm to split the text.
   - **Chunk Size (1000 characters)**: The text is cut into blocks of roughly 1000 characters.
   - **Chunk Overlap (200 characters)**: To prevent a sentence from being cut in half (which destroys its meaning), each chunk overlaps with the previous one by 200 characters. This preserves the semantic context across chunk boundaries.

---

## 6. Embeddings & Vectorization

Once a document is chunked, those text chunks are completely useless to a Vector Database until they are converted into mathematical arrays (Embeddings).

### Embedding Model: \`nomic-embed-text\`
- The system uses **Ollama** running locally to host the \`nomic-embed-text\` model.
- **Why Nomic?**: It is an extremely fast, open-weights embedding model that generates high-quality vectors with a dimensionality of \`768\`.
- **Privacy & Cost**: By running the embedding model locally via Ollama, sensitive document data is never sent to a third-party API (like OpenAI), and you incur absolutely zero cost for vectorizing massive documents.

### The Vectorization Process
1. The chunked text is sent to the local Ollama API.
2. Ollama returns a 768-dimensional float array for each chunk.
3. These arrays (along with the raw text payload and \`documentId\`) are saved into Qdrant.
4. During a chat query, the user's question is *also* passed through \`nomic-embed-text\` to generate a vector, and Qdrant uses **Cosine Similarity** to find the closest matching document chunks.

---

## 7. LLM Inference & Streaming

The final phase of the RAG pipeline is generating the human-readable answer.

### Generation Model: Sarvam AI (\`sarvam-105b\`)
- The backend connects to **Sarvam AI** (via an OpenAI-compatible LangChain wrapper).
- \`sarvam-105b\` is a massive, highly capable LLM chosen for its strong reasoning and generation capabilities.

### Prompt Orchestration
Before sending the request to Sarvam, the backend builds a massive context string:
1. It fetches the past 10 messages from PostgreSQL for **Chat Memory**.
2. It fetches the top 3 similar chunks from Qdrant for **Context Grounding**.
3. It combines these into a System Prompt: *"Answer the user based ONLY on the following context..."*

### Server-Sent Events (SSE)
Instead of waiting 10-15 seconds for Sarvam to generate the entire response, the backend opens a persistent SSE connection. As Sarvam generates each word (token), the backend immediately forwards that token to the Next.js frontend, creating a seamless, real-time typing effect for the user.
`;
